config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  resources :users

  get '/auth/:provider/callback', to: 'sessions#create'

  resources :schools do
    resources :ideas do
      member do
        post 'vote'
      end
    end
  end

  root 'ideas#index'

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  acts_as_votable

  belongs_to :user
  belongs_to :school
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :students, class_name: "User"
  has_many :ideas, through: :students
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :school

  has_many :ideas

  acts_as_voter

  def name
    "#{ first_name } #{ last_name }"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  skip_before_action :verify_authenticity_token

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy, :vote]
  before_action :set_school


  def vote
    @user = User.find(2)
    @idea.vote_by voter: @user, vote: 'like', duplicate: true

    respond_to do |wants|
      wants.json { render json: @idea.votes_for.size, status: :ok }
    end
  end

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = @school.ideas.all
    @idea = Idea.new
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to school_ideas_path(@school), notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:school_id])
    end

    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:body, :user_id, :school_id)
    end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    self.current_user = @user
    redirect_to school_ideas_url(1)
  end

  def new

  end

  protected
  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  end

  def index
  end

  def edit
  end

  def create
  end

  def update
  end

  def show
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/ideas/_form.html.erb
<%= form_for([@school, @idea]) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, size: "100x30" %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: 1 %>
  </div>
  <div class="field">
    <%= f.hidden_field :school_id, value: @school.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1>Ideas for <%= @school.name %></h1>

<div class="row">
  <div class="col-md-8">
    <div class="panel panel-default" style="background-color: #29ABE2; color: white;">
      <div class="panel-body">
        HOW MIGHT WE ...<br /><br />
        <%= form_for([@school, @idea]) do |f| %>
          <%= f.text_area :body, style: "width: 710px; height: 120px; color: #333; padding: 7px;", placeholder: "Enter an idea here..." %>
          ... TO IMPROVE <%= @school.name %>
          <%= f.hidden_field :user_id, value: 1 %>
          <%= f.hidden_field :school_id, value: @school.id %>
          <div class="col-md-offset-8" style="padding-left: 70px;">
            <%= f.submit "SUBMIT MY IDEA", class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div style="text-align: center;">
      <h1 style="color: #29ABE2;"><%= @school.ideas.size %></h1>
      <%= pluralize(@school.ideas.size, 'idea') %> submitted for <%= @school.name %>
    </div>
  </div>
</div>

<script type="text/javascript">
  function do_vote(idea) {
    var vote_url = 'http://0.0.0.0:3005/schools/<%= @school.id %>/ideas/' + idea + '/vote.json';
    var jqxhr = $.post(vote_url,
      function() { })
      .done(function(data) {
        var vote_str = (data > 1) ? " LIKES" : " LIKE";
        var vote_count_txt = '#votes-count-' + idea;
        $(vote_count_txt).html(data + vote_str);
      })
      .fail(function(data) {
        alert("Vote bombed!");
      });
  }

  $(function() {
    $("button[id^='idea-upvote-btn-']").on('click', function(e) {
      var which_idea = $(this).attr('id').split('-')[3];
      do_vote(which_idea);
    });
  });
</script>

<div class="row">

</div>
<% @ideas.each do |idea| %>
  <div class="row">
    <div class="col-md-10">
      <div class="col-md-8">
        <p>
          <%= idea.body %><br /><br />
          <p style="color: #777;">
            Submitted by <%= idea.user.name if @idea.user %>
          </p>
        </p>
        <hr />
      </div>
      <div class="col-md-2">
        <p style="text-align: center;">
          <button class="btn btn-success" style="margin-bottom: 3px;" id="idea-upvote-btn-<%= idea.id %>">
            LIKE
          </button><br />
          <span id="votes-count-<%= idea.id %>" style="color: #777;">
            <%= pluralize(idea.votes_for.size, "LIKE") %>
          </span>
        </p>
      </div>
    </div>
  </div>
<% end %>

<br>

app/views/ideas/new.html.erb
<h1>What's your idea?</h1>

<%= render 'form' %>

<%= link_to 'Back', school_ideas_path(@school) %>

app/views/ideas/show.html.erb
<p id="notice">
  <%= notice %>
</p>

<p>
  <strong>Body:</strong>
  <%= @idea.body %>
</p>

<p>
  Submitted by <%= @idea.user.name %>
</p>

<p>
  <strong>School:</strong>
  <%= @idea.school.name %>
</p>

<script type="text/javascript">
  function do_vote(vote) {
    var vote_url = '<%= vote_school_idea_path(@school, @idea, format: :json) %>?vote=' + vote;
    var jqxhr = $.post(vote_url,
      function() { })
      .done(function(data) {
        var vote_str = (data > 1) ? " upvotes" : " upvote";
        $('#votes-count').html(data + vote_str);
      })
      .fail(function(data) {
        alert("Vote bombed!");
      });
  }

  $(function() {
    $('#upvote-idea-btn').on('click', function(e) {
      e.preventDefault();
      do_vote('like');
    });
  });
</script>
<div>
  <span id="votes-count"><%= pluralize(@idea.votes_for.size, 'upvote') %></span>
</div>
<button id="upvote-idea-btn" class="btn btn-success">Upvote</button> <br /><br />
<%= link_to 'Edit', edit_school_idea_path(@school, @idea) %> |
<%= link_to 'Back', school_ideas_path(@school) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>How Might We...</title>
  <%= stylesheet_link_tag    'application', '//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'https://code.jquery.com/jquery-1.11.0.min.js', '//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1>Listing schools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.name %></td>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/user/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/user/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>

app/views/user/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>